services:
  who-profits-search-go:
    build: 
      context: .
      dockerfile: Dockerfile.go
    container_name: who-profits-search-go
    volumes:
      - ./output:/app/output
    environment:
      - OUTPUT_DIR=/app/output
      - LOG_LEVEL=INFO
    networks:
      - search-network
    restart: "no"

networks:
  search-network:
    driver: bridge